### PR TITLE
Merge master into MS branch

### PR DESCRIPTION
**Pull request by richardlford**
Merge from clang master branch into MS branch.

### CODE REVIEW

**Comment by richardlford** [comment]
Goes along with an LLVM FI.

**Comment by richardlford** [comment]
@adiaaida PTAL.

**Comment by adiaaida** [comment]
Is there something that needed to be changed/wasn't an auto FI? I don't think anyone is actively working on Clang, so this should be a clean merge. If so, LGTM.

**Comment by richardlford** [comment]
It was a clean merge. It just didn’t get FI’ed because the LLVM part failed.

**Pull request merged**
